### ISSUE TITLE
Lots of missing timezone ids

### ISSUE THREAD

**Issue by evansiroky** [shinnn/tz-ids#1]
There are a lot of missing ids in the array that is outputted.

For example:

`ETC/GMT`
`Pacific/Johnston`
`CST6CDT`

**Comment by shinnn** [comment]
This list is kept in sync with the latest IANA Time Zone Database extracted from https://www.iana.org/time-zones/repository/tzdata-latest.tar.gz . If you think something is missing, report it to the authors of the original data instead.

Don't forget to check the release announcements of the data before submitting any issues there. For example, https://mm.icann.org/pipermail/tz-announce/2019-March/000055.html explains why `Pacific/Johnston` was removed from the latest version.
